### ISSUE TITLE
Panic on session.ChannelVoiceJoin in deafened=false mode

### ISSUE THREAD

**Issue by khodand** [bwmarrin/discordgo#1161]
```panic: runtime error: slice bounds out of range [:4] with capacity 0

goroutine 89 [running]:
github.com/bwmarrin/discordgo.(*VoiceConnection).opusReceiver(0xc0004154a0, 0xc000092130, 0xc0000949c0, 0xc000176360)
        ***/vendor/github.com/bwmarrin/discordgo/voice.go:837 +0x59a
created by github.com/bwmarrin/discordgo.(*VoiceConnection).onEvent
       ***/vendor/github.com/bwmarrin/discordgo/voice.go:441 +0x6d8
 ```
       
I'm creating a music bot. When bot catch's the message event, it is initializing the voice connection. The bot connects to the voice channel, and after that it can accidentally throw a panic.

Connnecting:
```go
// (s *discordgo.Session, m *discordgo.MessageCreate)
        guild, err := s.State.Guild(m.GuildID)
	if err != nil {
		return "", err
	}
	id := ""
	for _, voiceState := range guild.VoiceStates {
		if voiceState.UserID == m.Author.ID {
			id = voiceState.ChannelID
			break
		}
	}
	c.session.ChannelVoiceJoin(m.GuildID, id, false, false)
```

**Comment by khodand** [comment]
There seems to be a panic on the calling ChannelVoiceJoin()
In `(s *Session) ChannelVoiceJoinManual`  websocket connection been called but it does not exists `s.wsConn == nil`
```
runtime.fatalpanic (panic.go:1271) runtime
runtime.gopanic (panic.go:1147) runtime
runtime.panicmem (panic.go:221) runtime
runtime.sigpanic (signal_windows.go:254) runtime
websocket.(*Conn).beginMessage (conn.go:479) github.com/gorilla/websocket
websocket.(*Conn).NextWriter (conn.go:520) github.com/gorilla/websocket
websocket.(*Conn).WriteJSON (json.go:24) github.com/gorilla/websocket
discordgo.(*Session).ChannelVoiceJoinManual (wsapi.go:722) github.com/bwmarrin/discordgo
discordgo.(*Session).ChannelVoiceJoin (wsapi.go:684) github.com/bwmarrin/discordgo
```
