### ISSUE TITLE
discordgo.User.AvatarURL("512") panics 

### ISSUE THREAD

**Issue by nullshii** [bwmarrin/discordgo#1531]
Getting avatar:
```go
interaction.User.AvatarURL("512")
```
Panics with error: **invalid memory address or nil pointer dereference**

-------

Full handler function:
```go
func PingCommand(s *discordgo.Session, i *discordgo.InteractionCreate) {
  if i.Type != discordgo.InteractionApplicationCommand || i.ApplicationCommandData().Name != "ping" {
    return
  }

  s.InteractionRespond(i.Interaction, &discordgo.InteractionResponse{
    Type: discordgo.InteractionResponseChannelMessageWithSource,
    Data: &discordgo.InteractionResponseData{
      Content: "Pong",
      Flags:   discordgo.MessageFlagsEphemeral,
      Embeds: []*discordgo.MessageEmbed{
          {
            Image: &discordgo.MessageEmbedImage{
            URL: i.User.AvatarURL("512"), //error happens here
          },
        },
      },
    },
  })
}
```

------

Full log:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x58 pc=0x54c3f2]

goroutine 43 [running]:
github.com/bwmarrin/discordgo.(*User).DefaultAvatarIndex(0xc000212a48?)
        C:/Users/nullshii/go/pkg/mod/github.com/bwmarrin/discordgo@v0.28.1/user.go:147 +0x12
github.com/bwmarrin/discordgo.(*User).AvatarURL(0x0, {0x607229, 0x5})
        C:/Users/nullshii/go/pkg/mod/github.com/bwmarrin/discordgo@v0.28.1/user.go:130 +0x26
descorde/internal/commands.PingCommand(0xc000004a88, 0xc000212a48)
        C:/Projects/go/descorde/internal/commands/ping.go:18 +0x11c
github.com/bwmarrin/discordgo.interactionCreateEventHandler.Handle(0x552dc8?, 0xc000004a88?, {0x5bae60?, 0xc000212a48?})
        C:/Users/nullshii/go/pkg/mod/github.com/bwmarrin/discordgo@v0.28.1/eventhandlers.go:714 +0x33
created by github.com/bwmarrin/discordgo.(*Session).handle in goroutine 38
        C:/Users/nullshii/go/pkg/mod/github.com/bwmarrin/discordgo@v0.28.1/event.go:171 +0x149
exit status 2
```

**Comment by nullshii** [comment]
For some reason if I Parse user from UserID and try to get avatar that way everything works 🤔.

Maybe I'm doing something wrong? Or is there better way to do it?

**Comment by FedorLap2006** [comment]
`interaction.User` is `nil` in guilds, and is replaced by `interaction.Member`.
It also contains the `User` object, so you might want to do something like this:
```go
user := i.User
if i.Member != nil {
    user = i.Member.User
}
```

**Comment by nullshii** [comment]
Thanks a lot! Fixed issue 😄
