### ISSUE TITLE
bug: nil pointer dereference while the bot was idling

### ISSUE THREAD

**Issue by pyrox777** [bwmarrin/discordgo#1547]
Hi there. I'm using discordgo v0.28.1 and while my bot was just idling (there was no slash command or message handling happening), it suddenly shut down with a panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x6b8db7]

goroutine 26 [running]:
github.com/bwmarrin/discordgo.(*Member).DisplayName(...)
        github.com/bwmarrin/discordgo@v0.28.1/structs.go:1591
lab.lostb.one/che/dimi/internal/pkg/dimi.logMessage(0xc000004a88, 0xc000066090)
        lab.lostb.one/che/dimi/internal/pkg/dimi/handlers.go:126 +0x1f7
lab.lostb.one/che/dimi/internal/pkg/dimi.messageHandler(0xc000004a88, 0xc000066090)
        lab.lostb.one/che/dimi/internal/pkg/dimi/handlers.go:250 +0x74
github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0x44445d?, 0x8?, {0x72e0a0?, 0xc000066090?})
        github.com/bwmarrin/discordgo@v0.28.1/eventhandlers.go:774 +0x33
created by github.com/bwmarrin/discordgo.(*Session).handle in goroutine 37
        github.com/bwmarrin/discordgo@v0.28.1/event.go:171 +0x149
```

Since this is the [return statement](
https://github.com/bwmarrin/discordgo/blob/da9e191069d09e1b467145f5758d9b11cb9cca0d/structs.go#L1591) of `*Member.DisplayName()`, I assume that `m.User.GlobalName` was not set.

Does the code need to check for nil for `m.User`? I don't know, just my first guess.

On second thought, it might be my code. I've added more extensive logging and will continue to monitor this and report back with new findings.

**Comment by pyrox777** [comment]
Okay, I figured it out. I have a logging function for messages and a message from another bot caused this crash. Apparently this bot (or bots in general) doesn't have `m.Member.User` set, so the call to `m.Member.DisplayName()` panicked.

I've added another check if `m.Member.User` is nil to handle this case, which fixed the problem.

Sorry for the noise, I'm closing this issue!
