### ISSUE TITLE
Gorilla websocket concurrency

### ISSUE THREAD

**Issue by bwmarrin** [bwmarrin/discordgo#30]
Per docs, 

Connections support one concurrent reader and one concurrent writer.

Applications are responsible for ensuring that no more than one goroutine calls the write methods (NextWriter, SetWriteDeadline, WriteMessage, WriteJSON) concurrently and that no more than one goroutine calls the read methods (NextReader, SetReadDeadline, ReadMessage, ReadJSON, SetPongHandler, SetPingHandler) concurrently.

The Close and WriteControl methods can be called concurrently with all other methods.

Need to setup a way to make sure this is done correctly in DiscrodGo

**Comment by bwmarrin** [comment]
Below example of an error that may be received due to this not being done yet..

```panic: concurrent write to websocket connection

goroutine 39 [running]:
panic(0x438bf60, 0xc8208ee0b0)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/gorilla/websocket.(*Conn).flushFrame(0xc820a04600, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/username/Desktop/Workspaces/Go/src/github.com/gorilla/websocket/conn.go:450 +0x5ba
github.com/gorilla/websocket.messageWriter.Close(0xc820a04600, 0x1, 0x0, 0x0)
    /Users/username/Desktop/Workspaces/Go/src/github.com/gorilla/websocket/conn.go:579 +0xa4
github.com/gorilla/websocket.(*messageWriter).Close(0xc8208ee010, 0x0, 0x0)
    <autogenerated>:7 +0xa4
github.com/gorilla/websocket.(*Conn).WriteJSON(0xc820a04600, 0x443b720, 0xc8208ee000, 0x0, 0x0)
    /Users/username/Desktop/Workspaces/Go/src/github.com/gorilla/websocket/json.go:27 +0x156
github.com/bwmarrin/discordgo.(*Session).heartbeat(0xc8200601c0, 0xc820a04600, 0xc8207c8c00, 0xa122)
    /Users/username/Desktop/Workspaces/Go/src/github.com/bwmarrin/discordgo/wsapi.go:191 +0x158
created by github.com/bwmarrin/discordgo.(*Session).onReady
    /Users/username/Desktop/Workspaces/Go/src/github.com/bwmarrin/discordgo/discord.go:240 +0x55```
