### ISSUE TITLE
heartbeat error in onResumed()

### ISSUE THREAD

**Issue by Krognol** [bwmarrin/discordgo#341]
```
Secsh channel 1 opened.
        /home/krognol/bot/src/github.com/bwmarrin/discordgo/event.go:237 +0x64
goroutine 2327 [IO wait]:
net.runtime_pollWait(0x7fdbf572ef88, 0x72, 0x3)
        /usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420287cd8, 0x72, 0x8a5a40, 0x8a2428)
        /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420287cd8, 0xc4203c0000, 0x2000)
        /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc420287c70, 0xc4203c0000, 0x2000, 0x2000, 0x0, 0x8a5a40, 0x8a2428)
        /usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42000e0b0, 0xc4203c0000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:181 +0x70
crypto/tls.(*block).readFromUntil(0xc420208930, 0x7fdbf572f1f0, 0xc42000e0b0, 0x5, 0xc42000e0b0, 0x198)
        /usr/local/go/src/crypto/tls/conn.go:488 +0x98
crypto/tls.(*Conn).readRecord(0xc420186000, 0x763b17, 0xc420186120, 0xc420629bf0)
        /usr/local/go/src/crypto/tls/conn.go:590 +0xc4
crypto/tls.(*Conn).Read(0xc420186000, 0xc4204ca000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1134 +0x11d
bufio.(*Reader).fill(0xc42040d1a0)
        /usr/local/go/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).Peek(0xc42040d1a0, 0x2, 0x0, 0xc4200e2078, 0xc420629f00, 0x663c50, 0xc4200e2000)
        /usr/local/go/src/bufio/bufio.go:129 +0x67
github.com/gorilla/websocket.(*Conn).read(0xc42043e8c0, 0x2, 0xc420188508, 0xc420629d70, 0x8a3940, 0xc420286620, 0xc4203a9500)
        /home/krognol/bot/src/github.com/gorilla/websocket/conn_read.go:12 +0x40
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc42043e8c0, 0x0, 0x0, 0x4affae)
        /home/krognol/bot/src/github.com/gorilla/websocket/conn.go:711 +0x5c
github.com/gorilla/websocket.(*Conn).NextReader(0xc42043e8c0, 0xc420629f00, 0x406f24, 0x6ce5e0, 0xc42040d200, 0x0)
        /home/krognol/bot/src/github.com/gorilla/websocket/conn.go:871 +0x82
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc42043e8c0, 0x1, 0xc42031c600, 0x81, 0x600, 0x0, 0x0)
        /home/krognol/bot/src/github.com/gorilla/websocket/conn.go:952 +0x2f
github.com/bwmarrin/discordgo.(*Session).listen(0xc4200e2000, 0xc42043e8c0, 0xc42040d200)
        /home/krognol/bot/src/github.com/bwmarrin/discordgo/wsapi.go:138 +0x8a
created by github.com/bwmarrin/discordgo.(*Session).Open
        /home/krognol/bot/src/github.com/bwmarrin/discordgo/wsapi.go:119 +0x5c6
```

**Comment by bwmarrin** [comment]
That's a heck of an error, never seen one like that before :(  Can you add any context, was your bot doing anything specific? Can you re-create the error? If so, by doing what?

I'm not sure what the error is either. I see a stack trace but not the error that caused it, is it just the "[IO Wait]" part? 😕 

Also, what version of DiscordGo are you using?  You might try switching to the current develop branch and see if that fixes your problem.

**Comment by Krognol** [comment]
Unfortunately I have no idea what the bot was doing or what was happening, so I can't really re-create it. I'm not sure what version of dgo I'm using but I can try updating it. The error hasn't re-occurred though.

**Comment by bwmarrin** [comment]
Just a follow up, have you had a run in with this error again?

**Comment by Krognol** [comment]
Nope, not once. I suspect it might have been something along the lines of forgetting to close a file or something in a separate goroutine. In any case, I'll close it, since it hasn't happened again.
