### ISSUE TITLE
Calling VoiceConnection.Disconnect() panic

### ISSUE THREAD

**Issue by albru123** [bwmarrin/discordgo#362]
I called `VoiceConnection.Disconnect()` on an opened connection (probably when packet was being sent, although I'm 99% it was called after I actually sent the data) and Gorilla just panicked, here's log:

```
panic: concurrent write to websocket connection

goroutine 95 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc0421fe090, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc0424bdb80)
	D:/Users/Albert/Documents/GoProjects/src/github.com/gorilla/websocket/conn.go:585 +0x582
github.com/gorilla/websocket.(*messageWriter).Close(0xc0421fe090, 0xc000000002, 0x9e4a40)
	D:/Users/Albert/Documents/GoProjects/src/github.com/gorilla/websocket/conn.go:699 +0x67
github.com/gorilla/websocket.(*Conn).prepWrite(0xc042203680, 0x1, 0x7c4480, 0xc042019900)
	D:/Users/Albert/Documents/GoProjects/src/github.com/gorilla/websocket/conn.go:468 +0x113
github.com/gorilla/websocket.(*Conn).NextWriter(0xc042203680, 0x1, 0x140db0, 0x0, 0x5d, 0xc0421321e0)
	D:/Users/Albert/Documents/GoProjects/src/github.com/gorilla/websocket/conn.go:488 +0x40
github.com/gorilla/websocket.(*Conn).WriteJSON(0xc042203680, 0x7c4480, 0xc0421f4120, 0xc0421f4120, 0x22)
	D:/Users/Albert/Documents/GoProjects/src/github.com/gorilla/websocket/json.go:22 +0x50
github.com/bwmarrin/discordgo.(*VoiceConnection).Disconnect(0xc0423062c0, 0x1, 0x1)
	D:/Users/Albert/Documents/GoProjects/src/github.com/bwmarrin/discordgo/voice.go:143 +0x1ed
main.(*Player).Stop(0xc04221ce00, 0x0, 0x0)
	D:/Users/Albert/Documents/GoProjects/src/github.com/albru123/tanuki-bot/music.go:476 +0x1bf
main.InitPlayer.func4(0x0, 0x0, 0x0, 0xc0423b8050, 0xc042112000, 0x0, 0x0)
	D:/Users/Albert/Documents/GoProjects/src/github.com/albru123/tanuki-bot/music.go:189 +0x61
main.ProcessCommand(0xc042112000, 0xc0423b8050, 0xc042110000)
	D:/Users/Albert/Documents/GoProjects/src/github.com/albru123/tanuki-bot/commands.go:77 +0x56c
main.handleCommand.func1(0xc042112000, 0xc0423b8050)
	D:/Users/Albert/Documents/GoProjects/src/github.com/albru123/tanuki-bot/main.go:66 +0x4f
github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0xc04200def0, 0xc042112000, 0x7a3640, 0xc0423b8050)
	D:/Users/Albert/Documents/GoProjects/src/github.com/bwmarrin/discordgo/eventhandlers.go:508 +0x5e
created by github.com/bwmarrin/discordgo.(*Session).handle
	D:/Users/Albert/Documents/GoProjects/src/github.com/bwmarrin/discordgo/event.go:158 +0xc9
```

**Comment by albru123** [comment]
Okay, my bad, it's probably fixed on develop. I'm not 100% sure, but it probably is.
