### ISSUE TITLE
Crash: MessageUpdate (EventHandler)

### ISSUE THREAD

**Issue by NaniteFactory** [bwmarrin/discordgo#737]
## My source code:
![주석 2020-02-13 040339](https://user-images.githubusercontent.com/10949969/74368596-537aea00-4e17-11ea-8324-8c52d360c1ca.png)

(It doesn't crash if I take away `onMessageUpdate()` part there.)

## Crash log:
```
2020-02-12T18:39:51.486105+00:00 app[worker.1]: panic: runtime error: invalid memory address or nil pointer dereference
2020-02-12T18:39:51.486130+00:00 app[worker.1]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6bd1f1]
2020-02-12T18:39:51.486131+00:00 app[worker.1]:
2020-02-12T18:39:51.486132+00:00 app[worker.1]: goroutine 53 [running]:
2020-02-12T18:39:51.486136+00:00 app[worker.1]: main.onMessageCommand(0xc0000f63c0, 0xc0004f2dc0)
2020-02-12T18:39:51.486196+00:00 app[worker.1]: /tmp/build_4e620c0faa73b43bc5aa38ffdaa56590/event.go:30 +0x51
2020-02-12T18:39:51.486299+00:00 app[worker.1]: main.onMessageUpdate(0xc0000f63c0, 0xc000332030)
2020-02-12T18:39:51.486404+00:00 app[worker.1]: /tmp/build_4e620c0faa73b43bc5aa38ffdaa56590/event.go:25 +0x38
2020-02-12T18:39:51.486584+00:00 app[worker.1]: github.com/bwmarrin/discordgo.messageUpdateEventHandler.Handle(0x78d488, 0xc0000f63c0, 0x716700, 0xc000332030)
2020-02-12T18:39:51.486686+00:00 app[worker.1]: /tmp/build_4e620c0faa73b43bc5aa38ffdaa56590/vendor/github.com/bwmarrin/discordgo/eventhandlers.go:617 +0x57
2020-02-12T18:39:51.486747+00:00 app[worker.1]: created by github.com/bwmarrin/discordgo.(*Session).handle
2020-02-12T18:39:51.486870+00:00 app[worker.1]: /tmp/build_4e620c0faa73b43bc5aa38ffdaa56590/vendor/github.com/bwmarrin/discordgo/event.go:171 +0x10e
2020-02-12T18:39:51.587355+00:00 heroku[worker.1]: State changed from up to crashed
2020-02-12T18:39:51.570719+00:00 heroku[worker.1]: Process exited with status 2
```

```
2020-02-12T18:28:28.152486+00:00 app[worker.1]: panic: runtime error: invalid memory address or nil pointer dereference
2020-02-12T18:28:28.152576+00:00 app[worker.1]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6bd1f1]
2020-02-12T18:28:28.152579+00:00 app[worker.1]:
2020-02-12T18:28:28.152690+00:00 app[worker.1]: goroutine 263 [running]:
2020-02-12T18:28:28.152761+00:00 app[worker.1]: main.onMessageCommand(0xc0000d63c0, 0xc0005cb4a0)
2020-02-12T18:28:28.152783+00:00 app[worker.1]: /tmp/build_4e620c0faa73b43bc5aa38ffdaa56590/event.go:30 +0x51
2020-02-12T18:28:28.152821+00:00 app[worker.1]: main.onMessageUpdate(0xc0000d63c0, 0xc000341af0)
2020-02-12T18:28:28.152845+00:00 app[worker.1]: /tmp/build_4e620c0faa73b43bc5aa38ffdaa56590/event.go:25 +0x38
2020-02-12T18:28:28.152894+00:00 app[worker.1]: github.com/bwmarrin/discordgo.messageUpdateEventHandler.Handle(0x78d488, 0xc0000d63c0, 0x716700, 0xc000341af0)
2020-02-12T18:28:28.152954+00:00 app[worker.1]: /tmp/build_4e620c0faa73b43bc5aa38ffdaa56590/vendor/github.com/bwmarrin/discordgo/eventhandlers.go:617 +0x57
2020-02-12T18:28:28.152975+00:00 app[worker.1]: created by github.com/bwmarrin/discordgo.(*Session).handle
2020-02-12T18:28:28.153000+00:00 app[worker.1]: /tmp/build_4e620c0faa73b43bc5aa38ffdaa56590/vendor/github.com/bwmarrin/discordgo/event.go:171 +0x10e
2020-02-12T18:28:28.241333+00:00 heroku[worker.1]: State changed from up to crashed
2020-02-12T18:28:28.229064+00:00 heroku[worker.1]: Process exited with status 2
```

## Environment
- Heroku
- Go 1.12.x
```
~ $ uname -a
Linux b3b19547-153f-4e65-8b36-08c10690fe9c 4.4.0-1057-aws #61+hf245703v20191104b1-Ubuntu SMP Mon Nov 4 15:32:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ewohltman** [comment]
Maybe a `MessageUpdate` event doesn't carry a non-nil `Author`?

```go
// The author of the message. This is not guaranteed to be a
// valid user (webhook-sent messages do not possess a full author).
Author *User `json:"author"`
```

https://github.com/bwmarrin/discordgo/blob/8416350234ae73804aa5828eee902283933e9368/message.go#L71

**Comment by NaniteFactory** [comment]
Yes, it looks like it's because I forgot to add a nil check for the `Author`. Everything works fine after I changed the code to this:
```Go
if evt.Author != nil {
	// Ignore all messages created by the bot itself.
	if evt.Author.ID == sess.State.User.ID {
		return
	}
}
```
Thank you very much! @ewohltman

**Comment by icanotc** [comment]
Had the same issue making a delete logger today
```go
func WatchDelete(s *discordgo.Session, m *discordgo.MessageDelete) {
        // nil check avoids the panic here
	if m.BeforeDelete != nil {
		fmt.Println("message deleted: " + m.BeforeDelete.Content)
	}
}
```
If the nil check wasn't there, the program will panic with a segmentation violation.
