### ISSUE TITLE
Missing Access 50001 for GuildMembers (out of nowhere)

### ISSUE THREAD

**Issue by Southclaws** [bwmarrin/discordgo#820]
Hey! Weird issue, probably not relevant to this codebase but it might be an API change.

The bot was running fine the day before, no code changes, no role changes (bot has all permissions anyway) and today, the call to `GuildMembers(app.config.GuildID, "", 1000)` just fails with "Missing Access". So after much discussion we came to the conclusion that the API changed on Discord's side.

Maybe something that needs to be updated here or something, or maybe it's a problem with an outdated usage of this function.

Here's the code anyway: https://github.com/Southclaws/cj/commit/6d9b89f79f40fcd12fb5029a9aa20b2465d9fa2f#diff-64ac3a5b7562d64a02d374d29eef9b49L163 we removed it because we had to.

**Comment by samuel-hunter** [comment]
Hi!
I've recently had a similar problem the same day this issue was made, and I've been following this in hopes that there's progress. My own personal bot errors with "Missing Access", and then _segfaults_ on a different event later on.

If I have time, I should plan to make a minimum-code bot to highlight the error.

**Comment by SonarBeserk** [comment]
@Southclaws @samuel-hunter I determined based on the notice in the api docs https://discord.com/developers/docs/resources/guild#list-guild-members and reviewing the bot section of the discord developer portal that they have put the server intent in place. 

```
Server Members Intent

If your bot tracks server members or downloads the entire member list, you may need the server members intent to receive member events and the member list.

NOTE: Once your bot reaches 100 or more servers, this will require Verification and whitelisting. Read more here
```

If you enable this option the error no longer occurs

**Comment by chand1012** [comment]
Was having the *exact* same issue, changed the setting mentioned by @SonarBeserk and it worked! The  on the bot page of the [Discord Developer Page](https://discord.com/developers). Its about halfway down, under "Privileged Gateway Intents".

![image](https://user-images.githubusercontent.com/3521582/95670199-608edb00-0b56-11eb-9b59-0e429cf40f89.png)

**Comment by Taycenn** [comment]
Can someone help me with a code error?
I have this code error in my console:

`
> discord-bot@1.0.0 deployCommands
> node src/deploy-commands.js

S[50001]: Missing Access
    at Q.runRequest (/home/taycen/Schreibtisch/Discord-Bot/node_modules/@discordjs/rest/dist/index.js:7:581)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Q.queueRequest (/home/taycen/Schreibtisch/Discord-Bot/node_modules/@discordjs/rest/dist/index.js:5:2942) {
  rawError: { message: 'Missing Access', code: 50001 },
  code: 50001,
  status: 403,
  method: 'put',
  url: 'https://discord.com/api/v9/applications/946831446071447612/guilds/932997267483418704/commands',
  requestBody: { files: undefined, json: [] }
}
`
I have no idea what it could be, hope someone can help me. 
Sincerely, Taycen

**Comment by FedorLap2006** [comment]
Not sure if this is related to DiscordGo, it looksl like Discord.JS code.
But from what I can tell, probably you just need to re-invite the bot with `applications.commands` oauth2 scope.

**Comment by Robinnnnn** [comment]
This began occurring for us once we updated the channel permissions that the bot was in! Hope this helps anyone else.
